language: csharp
solution: Introduction.sln
script:
  - grep "Test Results" build.log
dotnet: 2.0.0
dist: trusty
install:
  - dotnet restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - dotnet build
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ImageFiltersTest/bin/Debug/ImageFiltersTest.dll
notifications:
  email:
    recipients:
      - panmihaurkin@icloud.com
    on_success: never
    on_failure: always
