language: csharp
solution: Introduction.sln
install:
  - nuget restore Introduction.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Introduction.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./ImageFiltersTest/bin/Debug/ImageFiltersTest.dll
notifications:
  email:
    recipients:
      - panmihaurkin@icloud.com
    on_success: never
    on_failure: always
