language: csharp
solution: Introduction.sln
install:
  - nuget restore Introduction.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory TestResults
script:
  - xbuild /p:Configuration=Release Introduction.sln
  - mono ./TestResults/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./ImageFiltersTest/bin/Debug/ImageFiltersTest.dll
notifications:
  email:
    recipients:
      - panmihaurkin@icloud.com
    on_success: never
    on_failure: always
