language: csharp
solution: Introduction.sln
script:
  - grep "Test Results" build.log
dotnet: 2.0.0
dist: trusty
install:
  - nuget restore Introduction.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Introduction.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./ImageFiltersTest/bin/x64/Release/ImageFiltersTest.dll
notifications:
  email:
    recipients:
      - panmihaurkin@icloud.com
    on_success: always
    on_failure: never
